# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 2dec5ff76c784ab2695ffeab978238d05ee8287bb6ab2f4589bd942c409c755f236e1ba1a4917d2348939f4f72a581880bf689c65e3d9482339464a65915f370

test:
  secret_key_base: 9290ccfebc5292a1f5d0b22f692720bef8d5c35559620bfab81c11a5db70dd23eb67ca7a649ccf8f73be6625f9004792732492e4bcc4e2cce8e08949bc9f5390

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
